apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: cassandra
        resources:
          requests:
        ports:
        - containerPort: 9042
        env:
          - name: HEAP_NEWSIZE
            value: 128M
          - name: MAX_HEAP_SIZE
            value: 256M
---
