FROM python:3.6-slim
RUN  pip3 install pika redis flask flask_table requests jsonpickle flask_cors
RUN  pip3 install cassandra-driver
WORKDIR /srv
COPY    rest-server.py /srv
CMD [ "python3", "rest-server.py"]
