apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: rest-server
spec:
  selector:
    matchLabels:
      app: rest-server
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-server
    spec:
      containers:
      - name: rest-server
        image: audioid-rest
        imagePullPolicy: Never
        # image: 001cat/audioid-rest:latest
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: CASSANDRA_HOST
          value: cassandra
        - name: RABBITMQ_HOST
          value: rabbitmq
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /srv/uploads
          name: mp3uploads
      volumes:
      - name: mp3uploads
        persistentVolumeClaim:
          claimName: mp3pvc
