apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: worker-server
spec:
  selector:
    matchLabels:
      app: worker-server
  replicas: 2
  template:
    metadata:
      labels:
        app: worker-server
    spec:
      containers:
      - name: worker-server
        image: 001cat/audioid-worker:latest
        # imagePullPolicy: Never
        # image: audioid-worker
        resources:
          requests:
            # cpu: 800m
            # memory: 1000Mi
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: CASSANDRA_HOST
          value: cassandra
        volumeMounts:
        - mountPath: /srv/uploads
          name: mp3uploads
      volumes:
      - name: mp3uploads
        persistentVolumeClaim:
          claimName: mp3pvc
